# These are supported funding model platforms

github: valzzu # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: iris_the_elf # Replace with a single Patreon username
